### ISSUE TITLE
Atributo date não funciona no Mozilla Firefox

### ISSUE THREAD

**Issue by felipewmartins** [bytecomoficial/SICOBA#101]
Campos com do tipo <input type="date"> não funcionam no firefox.
Testado com a versão: Firefox 31.0

**Comment by clairtonluz** [comment]
Não vamos mais usar o date do html por causa da falta de compatibilidade com o firefox, desda versão 31 foi registrado esse bug e já estamos na versão 35 e a firefox não resolveu.

**Comment by felipewmartins** [comment]
É osso, firefox atrasado mesmo :/
