### ISSUE TITLE
implementar o uso do weld para os testes unitários: WeldJUnit4Runner

### ISSUE THREAD

**Issue by clairtonluz** [bytecomoficial/sicoba#127]

**Comment by felipewmartins** [comment]
Como seria essa implementação?

**Comment by clairtonluz** [comment]
Só configurar o Weld com o JUnit para Fazer os teste de integração. Usar o
@Inject para injetar o ClienteJPA nos teste unitário por exemplo.

--

Att. Clairton Luz - Jr. Java Dev.

*Blog: https://clairtondev.wordpress.com
<https://clairtondev.wordpress.com>* <http://clairtonluz.github.io/>* | *
*Github: *https://github.com/clairtonluz

**Comment by felipewmartins** [comment]
Massa,
 Da pra usar o weld padrão do Wildfly? Ou teria que adicionar a dependência
no pom.xml? :)

Em 9 de março de 2015 13:55, Clairton Luz <notifications@github.com>
escreveu:

> Só configurar o Weld com o JUnit para Fazer os teste de integração. Usar o
> @Inject para injetar o ClienteJPA nos teste unitário por exemplo.
>
> --
>
> Att. Clairton Luz - Jr. Java Dev.
>
> *Blog: https://clairtondev.wordpress.com
> <https://clairtondev.wordpress.com>* <http://clairtonluz.github.io/>* | *
> *Github: *https://github.com/clairtonluz
>
> On Sun, Mar 8, 2015 at 1:51 PM, Felipe Martins <notifications@github.com>
> wrote:
>
> > Como seria essa implementação?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/bytecomoficial/SICOBA/issues/127#issuecomment-77760689>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bytecomoficial/SICOBA/issues/127#issuecomment-77894367>
> .
>



-- 
Felipe Wender Mendonça Martins
Graduando em Análise e Desenvolvimento de Sistemas
#blog: http://felipewmartins.github.io/
Fatene

**Comment by clairtonluz** [comment]
o que preferir tá bom.

**Comment by clairtonluz** [comment]
Olá, Responder,,

Você recebeu um convite de Clairton para se inscrever no Campeonato Universitário do Dropbox! No Campeonato Universitário, você e seus colegas se juntam para ganhar até 25 GB de espaço gratuito no Dropbox por dois anos!

Para ganhar espaço, convide amigos e use o Dropbox para compartilhar arquivos, trabalhar em equipe e cuidar de projetos.

Entre no Campeonato Universitário![2]

Observe que, para participar, é preciso ser um aluno atualmente matriculado em uma instituição de ensino superior. Saiba mais sobre o Campeonato Universitário.[3]

Divirta-se com o Dropbox!


 
 Trabalhe em equipe, ganhe em equipe.

____________________________________________________
Se preferir não receber convites do Dropbox, acesse esta página[42].
Dropbox, Inc., PO Box 77767, San Francisco, CA 94107

[1]: https://www.dropbox.com/l/nfcqspuhwvGtWRo9oKC6bv/campuscup?text=1
[2]: https://www.dropbox.com/l/azoSb9sY9kofCluvEXEaYC/campuscup?text=1
[3]: https://www.dropbox.com/l/RWLFeMepNsoWAUdrRjyYAf/help/9131?text=1
[4]: https://www.dropbox.com/l/OU54ZCGm0D6IgojN7xA2on?text=1
