### ISSUE TITLE
Geocodificação incorreta

### ISSUE THREAD

**Issue by felipewmartins** [bytecomoficial/SICOBA#155]
Notei que em endereços com numerações Ex: Rua 1025. O geocode "engole" a numeração, mesmo esta sendo string. Mandei essa duvida pro fórum da google, já que estamos usando codificação UTF-8. Em endereços alfa, esse problema não ocorre.

**Comment by clairtonluz** [comment]
ok

**Comment by felipewmartins** [comment]
Percebi que não é a codificação que está incorreta. No google maps, por exemplo, a Rua 1147, está como "Mil Cento e quarenta e Sete", por isso o google não encontra o endereço

**Comment by felipewmartins** [comment]
Não é bug. As ruas podem ser ajustadas no google maps.
